### ISSUE TITLE
图片资源404

### ISSUE THREAD

**Issue by sonderlau** [AnRFDev/Tutorial2020#1]
在阅读RecyclerView的使用示例时 有图片失效
![image](https://user-images.githubusercontent.com/12829325/95648014-9df65880-0ac3-11eb-83c4-1dbb565ecf7e.png)
瀑布流中也有失效的图片
![image](https://user-images.githubusercontent.com/12829325/95648037-c9794300-0ac3-11eb-9370-7047b02193f1.png)
翻了翻 好像别的章节也有些图片失效了

**Comment by RustFisher** [comment]
有些图片是放在cdn里的，协议是http。而站点是https的，因此显示不正常。
正在想办法解决。

**Comment by RustFisher** [comment]
已将那部分图片转移到服务器上
